name: better_player
description: Advanced video player based on video_player and Chewie. It's solves many typical use cases and it's easy to run.
version: 0.0.83
# Disabled because of warning from analyzer
# authors:
#  - Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/betterplayer
documentation: https://jhomlala.github.io/betterplayer/

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.2.3"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  meta: ^1.7.0
  flutter_widget_from_html_core: ^0.10.3
  visibility_detector: ^0.3.3
  path_provider: ^2.0.15
  collection: ^1.16.0
  xml: ^6.1.0
  flutter_to_airplay:
    git:
      url: https://github.com/picasso-one/flutter_to_airplay_fork.git
      ref: develop
    #leave below for development and testing purposes
    #path: ../flutter_to_airplay_fork
dev_dependencies:
  lint: ^2.1.2
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.jhomlala.better_player
        pluginClass: BetterPlayerPlugin
      ios:
        pluginClass: BetterPlayerPlugin